name: PR
on:
  pull_request_target:
    types:
      - opened
      - edited
      - ready_for_review
      - synchronize
  issue_comment:
    types: [created, edited]
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Approvers
        id: approvers
        run: echo ::set-output name=approvers::$(cat ./OWNERS)

      - name: Add Approved label
        if: |
          contains(github.event.comment.html_url, '/pull/') &&
          (contains(github.event.comment.body, '/approve') || contains(github.event.comment.body, '/lgtm')) &&
          contains(steps.approvers.outputs.approvers, github.event.comment.user.login || 'null')
        uses: andymckay/labeler@master
        with:
          add-labels: 'approved'

      - name: Add LGTM label
        if: |
          contains(github.event.comment.html_url, '/pull/') && 
          contains(github.event.comment.body, '/lgtm') &&
          contains(steps.approvers.outputs.approvers, github.event.comment.user.login || 'null') &&
          github.event.issue.user.login != github.event.comment.user.login
        uses: andymckay/labeler@master
        with:
          add-labels: 'lgtm'
          remove-labels: 'WIP'

      - name: Remove LGTM Label if new push is made
        if: |
         github.event_name == 'pull_request' && github.event.action == 'synchronize' &&
         contains(github.event.pull_request.labels.*.name, 'lgtm')
        uses: andymckay/labeler@master
        with:
          remove-labels: 'lgtm'

      - name: Add WIP label / comment trigger
        if: |
          contains(github.event.pull_request.title, 'wip') ||
          (contains(github.event.comment.html_url, '/pull/') && 
          contains(github.event.comment.body, '/wip'))
        uses: andymckay/labeler@master
        with:
          add-labels: 'WIP'

      - name: Remove WIP label
        if: |
          contains(github.event.comment.html_url, '/pull/') && 
          contains(github.event.comment.body, '/remove wip')
        uses: andymckay/labeler@master
        with:
          remove-labels: 'WIP'

      - name: Add Hold label
        if: |
          contains(github.event.comment.html_url, '/pull/') && 
          contains(github.event.comment.body, '/hold') &&
          contains(steps.approvers.outputs.approvers, github.event.comment.user.login || 'null')
        uses: andymckay/labeler@master
        with:
          add-labels: 'hold'

      - name: Remove Hold label
        if: |
          contains(github.event.comment.html_url, '/pull/') && 
          contains(github.event.comment.body, '/remove hold') &&
          contains(steps.approvers.outputs.approvers, github.event.comment.user.login || 'null')
        uses: andymckay/labeler@master
        with:
          remove-labels: 'hold'

      - name: Add Bug label / comment trigger
        if: |
          contains(github.event.pull_request.title, 'bug') ||
          (contains(github.event.comment.html_url, '/pull/') && 
          contains(github.event.comment.body, '/bug'))
        uses: andymckay/labeler@master
        with:
          add-labels: 'bug'
      
      - name: Add Size label
        uses: "pascalgn/size-label-action@v0.4.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
